version: 2

sources:
    - name: staging
      #For bigquery:
      database: datatalksclub-380013
      
      # For postgres:
      #database: production

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: rides
         # freshness:
           # error_after: {count: 6, period: hour}
